apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-simple-clone
spec:
  params:
    - name: pipeline-pvc
      description: the pipeline pvc name
    - name: pipelineRunId
      description: pipelineRunId unique ID
    - name: repository
      description: the git repo
    - name: branch
      description: the branch for the git repo
    - name: pathToDockerfile
      default: '.'
    - name: pipeline-debug
      default: "0"
    - name: cluster-name
      description: the name of the cluster to target
    - name: dev-cluster-namespace
      description: the namespace
    - name: registry-region
      description: The IBM Cloud region for image registry
    - name: apikey
      description: The IBM Cloud API key is used to access the IBM Cloud Kubernetes
        Service API and interact with the cluster. You can obtain your API key with
        'bx iam api-key-create' or via the console at https://cloud.ibm.com/iam#/apikeys
        by clicking **Create API key** (Each API key only can be viewed once).
    - name: revision
      description: the branch for the git repo
  #resources:
  #- name: app-image
  #  type: image
  #- name: target-cluster
  #  type: cluster
  tasks:
    - name: fetch-code
      taskRef:
        name: git-clone-repo