apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-simple-clone
spec:
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: fetch-code
      taskRef:
        name: git-clone-repo
      workspaces:
        - name: workspace
          workspace: pipeline-ws