apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-container-registry
spec:
  params:
    - name: repository
      description: the git repo
    - name: branch
      description: the branch for the git repo
    - name: path-to-dockerfile
      default: '.'
    - name: pipeline-debug
      default: "0"
    - name: cluster-name
      description: the name of the cluster to target
    - name: dev-cluster-namespace
      description: the namespace
    - name: registry-region
      description: The IBM Cloud region for image registry
  resources:
  - name: app-image
    type: image
  - name: target-cluster
    type: cluster
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: pipeline-1-clone-task
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
      workspaces:
        - name: workspace
          workspace: pipeline-ws
    - name: docker-lint-task
      runAfter: [pipeline-1-clone-task]
      taskRef:
        name: docker-check-task
      workspaces:
        - name: workspace
          workspace: pipeline-ws
    - name: docker-lint-task2
      runAfter: [docker-lint-task]
      taskRef:
        name: docker-check-task2
      workspaces:
        - name: workspace
          workspace: pipeline-ws
    - name: deploy-dev
      taskRef:
        name: deploy-to-cluster
      runAfter: [docker-lint-task2]
      params:
        - name: repository
          value: $(params.repository)
        - name: cluster-name
          value: $(params.cluster-name)
        - name: cluster-namespace
          value: $(params.dev-cluster-namespace)
        - name: cluster-region
          value: $(params.registry-region)
        - name: allow-create-route
          value: "true"
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: cluster-region
          value: $(params.registry-region)
      workspaces:
        - name: workspace
          workspace: pipeline-ws
